# Final Project

Battle Royale-style video games have taken the world by storm. 100 players are dropped onto an island
empty-handed and must explore, scavenge, and eliminate other players until only one is left standing, all
while the play zone continues to shrink.

Data Science Essentials | November 2020

PlayerUnknown's BattleGrounds (PUBG) has enjoyed massive popularity. With over 50 million copies
sold, it's the fifth best selling game of all time, and has millions of active monthly players.
The team at PUBG has made official game data available for the public to explore and scavenge outside
of "The Blue Circle." This competition is not an official or affiliated PUBG site - Kaggle collected data made
possible through the PUBG Developer API.
You are given over 65,000 games' worth of anonymized player data, split into training and testing sets,
and asked to predict final placement from final in-game stats and initial player ratings.
What's the best strategy to win in PUBG? Should you sit in one spot and hide your way into victory, or do
you need to be the top shot? Let's let the data do the talking!
Dataset’s columns Description:
groupId - Integer ID to identify a group within a match. If the same group of players plays in different
matches, they will have a different groupId each time.
matchId - Integer ID to identify match. There are no matches that are in both the training and testing set.
assists - Number of enemy players this player damaged that were killed by teammates.
boosts - Number of boost items used.
damageDealt - Total damage dealt. Note: Self inflicted damage is subtracted.
DBNOs - Number of enemy players knocked.
headshotKills - Number of enemy players killed with headshots.
heals - Number of healing items used.
killPlace - Ranking in match of number of enemy players killed.
killPoints - Kills-based external ranking of player. (Think of this as an Elo ranking where only kills matter.)
kills - Number of enemy players killed.
killStreaks - Max number of enemy players killed in a short amount of time.
longestKill - Longest distance between player and player killed at time of death. This may be misleading,
as downing a - player and driving away may lead to a large longestKill stat.
maxPlace - Worst placement we have data for in the match. This may not match with numGroups, as
sometimes the data skips over placements.
numGroups - Number of groups we have data for in the match.
revives - Number of times this player revived teammates.

Data Science Essentials | November 2020

rideDistance - Total distance traveled in vehicles measured in meters.
roadKills - Number of kills while in a vehicle.
swimDistance - Total distance traveled by swimming measured in meters.
teamKills - Number of times this player killed a teammate.
vehicleDestroys - Number of vehicles destroyed.
walkDistance - Total distance traveled on foot measured in meters.
weaponsAcquired - Number of weapons picked up.
winPoints - Win-based external ranking of player. (Think of this as an Elo ranking where only winning
matters.)
winPlacePerc - The target of prediction. This is a percentile winning placement, where 1 corresponds to
1st place, and 0 corresponds to last place in the match. It is calculated off of maxPlace, not numGroups,
so it is possible to have missing chunks in a match.

# 1

In [12]:
import pandas as pd

data = pd.read_csv('pubg - Dr. Darshan Ingle.csv')

data.head()

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,...,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,2f262dd9795e60,78437bcd91d40e,d5db3a49eb2955,0,0,0.0,0,0,0,92,...,0,0.0,0,0.0,0,0,0.0,0,1470,0.0000
1,a32847cf5bf34b,85b7ce5a12e10b,65223f05c7fdb4,0,0,163.2,1,1,0,42,...,0,0.0,0,0.0,0,0,132.7,2,1531,0.2222
2,1b1900a9990396,edf80d6523380a,1cadec4534f30a,0,3,278.7,2,1,8,16,...,3,0.0,0,0.0,0,0,3591.0,10,0,0.8571
3,f589dd03b60bf2,804ab5e5585558,c4a5676dc91604,0,0,191.9,1,0,0,31,...,0,0.0,0,0.0,0,0,332.7,3,0,0.3462
4,c23c4cc5b78b35,b3e2cd169ed920,cd595700a01bfa,0,0,100.0,1,0,0,87,...,0,0.0,0,0.0,0,0,252.7,3,1557,0.0690

# 2

In [14]:
data.dtypes

Id                  object
groupId             object
matchId             object
assists              int64
boosts               int64
damageDealt        float64
DBNOs                int64
headshotKills        int64
heals                int64
killPlace            int64
killPoints           int64
kills                int64
killStreaks          int64
longestKill        float64
matchDuration        int64
matchType           object
maxPlace             int64
numGroups            int64
rankPoints           int64
revives              int64
rideDistance       float64
roadKills            int64
swimDistance       float64
teamKills            int64
vehicleDestroys      int64
walkDistance       float64
weaponsAcquired      int64
winPoints            int64
winPlacePerc       float64
dtype: object

# 3

In [18]:
data.describe().columns

data.describe()

numerical_cols= data.describe().columns

df=data[numerical_cols]
df

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,kills,killStreaks,...,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,0,0,0.0,0,0,0,92,1126,0,0,...,0,0.0,0,0.0,0,0,0.00,0,1470,0.0000
1,0,0,163.2,1,1,0,42,1309,1,1,...,0,0.0,0,0.0,0,0,132.70,2,1531,0.2222
2,0,3,278.7,2,1,8,16,0,2,1,...,3,0.0,0,0.0,0,0,3591.00,10,0,0.8571
3,0,0,191.9,1,0,0,31,0,1,1,...,0,0.0,0,0.0,0,0,332.70,3,0,0.3462
4,0,0,100.0,1,0,0,87,1332,0,0,...,0,0.0,0,0.0,0,0,252.70,3,1557,0.0690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,204.5,1,0,0,17,1033,2,1,...,3,0.0,0,0.0,0,0,1648.00,4,1471,0.8333
9996,0,0,0.0,0,0,0,49,1000,0,0,...,0,0.0,0,0.0,0,0,897.10,6,1500,0.7174
9997,0,0,0.0,0,0,0,83,1334,0,0,...,0,0.0,0,0.0,0,0,188.20,2,1434,0.2083
9998,0,0,0.0,0,0,0,82,1335,0,0,...,0,0.0,0,0.0,0,0,108.10,5,1534,0.2449
9999,0,0,0.0,0,0,0,78,0,0,0,...,0,0.0,0,0.0,0,0,53.36,1,0,0.1875

# 4

In [19]:
data['kills'].mean()

0.9134

# 5

In [21]:
df = pd.DataFrame(data)
df

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,...,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,2f262dd9795e60,78437bcd91d40e,d5db3a49eb2955,0,0,0.0,0,0,0,92,...,0,0.0,0,0.0,0,0,0.00,0,1470,0.0000
1,a32847cf5bf34b,85b7ce5a12e10b,65223f05c7fdb4,0,0,163.2,1,1,0,42,...,0,0.0,0,0.0,0,0,132.70,2,1531,0.2222
2,1b1900a9990396,edf80d6523380a,1cadec4534f30a,0,3,278.7,2,1,8,16,...,3,0.0,0,0.0,0,0,3591.00,10,0,0.8571
3,f589dd03b60bf2,804ab5e5585558,c4a5676dc91604,0,0,191.9,1,0,0,31,...,0,0.0,0,0.0,0,0,332.70,3,0,0.3462
4,c23c4cc5b78b35,b3e2cd169ed920,cd595700a01bfa,0,0,100.0,1,0,0,87,...,0,0.0,0,0.0,0,0,252.70,3,1557,0.0690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ef4f474acd8e85,2eca2a8391f75d,492ecdfae90b46,0,3,204.5,1,0,0,17,...,3,0.0,0,0.0,0,0,1648.00,4,1471,0.8333
9996,cf0bf82fb4d80e,2eaf2765f93adb,14bffd71e96320,0,0,0.0,0,0,0,49,...,0,0.0,0,0.0,0,0,897.10,6,1500,0.7174
9997,a0a31a0b1dcbe1,8d50c64ccc5071,147e4bbb62e3bb,0,0,0.0,0,0,0,83,...,0,0.0,0,0.0,0,0,188.20,2,1434,0.2083
9998,f6874657399d69,d31843d7e62ccb,662567dcf280f5,0,0,0.0,0,0,0,82,...,0,0.0,0,0.0,0,0,108.10,5,1534,0.2449
9999,90359b0b8f8b0d,61d5b1bb8da43f,258bfa48d88014,0,0,0.0,0,0,0,78,...,0,0.0,0,0.0,0,0,53.36,1,0,0.1875

In [33]:
df['kills'].describe([.01,.1,.2,.3,.4,.5,.6,.7,.8,.9,.99])

count    10000.000000
mean         0.913400
std          1.524117
min          0.000000
1%           0.000000
10%          0.000000
20%          0.000000
30%          0.000000
40%          0.000000
50%          0.000000
60%          1.000000
70%          1.000000
80%          2.000000
90%          3.000000
99%          7.000000
max         35.000000
Name: kills, dtype: float64

# 6

In [37]:
df['kills'].describe()

count    10000.000000
mean         0.913400
std          1.524117
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max         35.000000
Name: kills, dtype: float64